spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:mypass}

  jpa:
    show-sql: true

  flyway:
    locations: classpath:db/migration,classpath:dev/db/migration
