spring:
  application:
    name: jpa-spec-dynamic-search-engine
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  web:
    resources:
      add-mappings: false
  flyway:
    locations: classpath:db/migration
  sql:
    init:
      mode: never
server:
  port: 8080
