
CREATE TABLE publishers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    founded_year INTEGER
    );

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id BIGINT NOT NULL ,
    title VARCHAR(100) NOT NULL,
    genre VARCHAR(50),
    price  NUMERIC(12,2) NOT NULL,
    publish_year  INTEGER,
    availability BOOLEAN NOT NULL,
    CONSTRAINT fk_books_publisher
    FOREIGN KEY (publisher_id) REFERENCES publishers(id)
    );

CREATE TABLE book_authors (
    book_id BIGINT NOT NULL,
    author VARCHAR(100) NOT NULL,
    CONSTRAINT fk_book_authors_book
    FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE INDEX idx_books_title ON books(title);
CREATE INDEX idx_books_genre ON books(genre);
CREATE INDEX idx_books_publish_year ON books(publish_year);
CREATE INDEX idx_books_availability ON books(availability);
CREATE INDEX idx_books_publisher_id ON books(publisher_id);
CREATE INDEX idx_book_authors_book_id ON book_authors(book_id);
