-- Demo seed data only.
-- Some records were AI-generated and have not been fully fact-checked.

-- ==============================
-- PUBLISHERS
-- ==============================
INSERT INTO publishers (id, name, founded_year) VALUES
                                                    (1, 'Penguin Random House', 1960),
                                                    (2, 'OReilly Media', 1950),
                                                    (3, 'HarperCollins', 2008),
                                                    (4, 'Springer', 1930),
                                                    (5, 'Packt Publishing', 2000),
                                                    (6, 'Addison-Wesley', 2013),
                                                    (7, 'Manning Publications', 1978),
                                                    (8, 'Simon & Schuster', 2001),
                                                    (9, 'No Starch Press', 2010),
                                                    (10, 'Apress', 1980);

-- ==============================
-- BOOKS
-- ==============================
INSERT INTO books (id, title, genre, price, publish_year, availability, publisher_id) VALUES
                                                                                          (1, 'Effective Java', 'Programming', 45.50, 2018, TRUE, 6),
                                                                                          (2, 'Clean Code', 'Programming', 42.00, 2017, FALSE, 6),
                                                                                          (3, 'Clean Architecture', 'Programming', 39.00, 2019, TRUE, 6),
                                                                                          (4, 'Head First Java', 'Programming', 35.00, 2015, TRUE, 1),
                                                                                          (5, 'Java Concurrency in Practice', 'Programming', 48.00, 2016, TRUE, 6),
                                                                                          (6, 'Spring in Action', 'Programming', 44.99, 2021, TRUE, 7),
                                                                                          (7, 'Spring Boot Up and Running', 'Programming', 40.00, 2020, FALSE, 2),
                                                                                          (8, 'Pro Spring Boot', 'Programming', 38.50, 2020, TRUE, 10),
                                                                                          (9, 'Beginning Spring Boot 3', 'Programming', 33.00, 2023, TRUE, 10),
                                                                                          (10, 'Java Puzzlers', 'Programming', 36.00, 2014, TRUE, 6),

                                                                                          (11, 'The Pragmatic Programmer', 'Programming', 41.00, 1999, TRUE, 6),
                                                                                          (12, 'Refactoring', 'Programming', 50.00, 2018, TRUE, 6),
                                                                                          (13, 'Design Patterns', 'Programming', 47.00, 1994, TRUE, 6),
                                                                                          (14, 'Algorithms Unlocked', 'Computer Science', 30.00, 2016, TRUE, 4),
                                                                                          (15, 'Introduction to Algorithms', 'Computer Science', 65.00, 2022, TRUE, 4),
                                                                                          (16, 'Artificial Intelligence: A Modern Approach', 'AI', 70.00, 2021, TRUE, 4),
                                                                                          (17, 'Deep Learning with Python', 'AI', 55.00, 2020, TRUE, 2),
                                                                                          (18, 'Hands-On Machine Learning', 'AI', 58.00, 2022, TRUE, 2),
                                                                                          (19, 'Python Crash Course', 'Programming', 39.99, 2021, FALSE, 9),
                                                                                          (20, 'Automate the Boring Stuff', 'Programming', 32.50, 2020, TRUE, 9),

                                                                                          (21, 'Learning SQL', 'Database', 29.99, 2019, TRUE, 2),
                                                                                          (22, 'SQL Cookbook', 'Database', 35.00, 2020, TRUE, 2),
                                                                                          (23, 'MongoDB: The Definitive Guide', 'Database', 37.00, 2022, TRUE, 2),
                                                                                          (24, 'Pro MySQL Development', 'Database', 44.00, 2020, FALSE, 10),
                                                                                          (25, 'Data Modeling Made Simple', 'Database', 31.00, 2018, TRUE, 3),

                                                                                          (26, 'The Great Gatsby', 'Fiction', 10.99, 1925, TRUE, 3),
                                                                                          (27, '1984', 'Fiction', 12.50, 1949, TRUE, 3),
                                                                                          (28, 'To Kill a Mockingbird', 'Fiction', 11.00, 1960, TRUE, 3),
                                                                                          (29, 'The Catcher in the Rye', 'Fiction', 10.50, 1951, TRUE, 3),
                                                                                          (30, 'Brave New World', 'Fiction', 13.00, 1932, TRUE, 3),

                                                                                          (31, 'Modern Java Recipes', 'Programming', 37.00, 2017, TRUE, 5),
                                                                                          (32, 'Java 8 in Action', 'Programming', 40.00, 2015, TRUE, 6),
                                                                                          (33, 'Java Performance', 'Programming', 49.00, 2021, TRUE, 6),
                                                                                          (34, 'Kotlin in Action', 'Programming', 42.00, 2020, TRUE, 7),
                                                                                          (35, 'Spring Microservices in Action', 'Programming', 46.00, 2019, TRUE, 7),

                                                                                          (36, 'Deep Learning Illustrated', 'AI', 54.00, 2021, TRUE, 1),
                                                                                          (37, 'TensorFlow for Beginners', 'AI', 45.00, 2020, TRUE, 10),
                                                                                          (38, 'Data Science from Scratch', 'AI', 47.00, 2019, TRUE, 2),
                                                                                          (39, 'Machine Learning Yearning', 'AI', 50.00, 2018, FALSE, 2),
                                                                                          (40, 'AI Superpowers', 'AI', 35.00, 2019, TRUE, 3),

                                                                                          (41, 'The Clean Coder', 'Programming', 39.00, 2016, TRUE, 6),
                                                                                          (42, 'Domain-Driven Design', 'Programming', 55.00, 2015, TRUE, 6),
                                                                                          (43, 'Building Microservices', 'Architecture', 49.00, 2022, TRUE, 2),
                                                                                          (44, 'Software Architecture Patterns', 'Architecture', 36.00, 2020, TRUE, 2),
                                                                                          (45, 'Enterprise Integration Patterns', 'Architecture', 52.00, 2003, TRUE, 6),

                                                                                          (46, 'Kafka in Action', 'Architecture', 46.00, 2021, TRUE, 7),
                                                                                          (47, 'RabbitMQ Essentials', 'Architecture', 33.00, 2019, TRUE, 10),
                                                                                          (48, 'Cloud Native Java', 'Programming', 50.00, 2018, TRUE, 7),
                                                                                          (49, 'Pro Docker', 'DevOps', 42.00, 2020, TRUE, 10),
                                                                                          (50, 'Kubernetes Up and Running', 'DevOps', 48.00, 2021, TRUE, 2),

                                                                                          (51, 'Linux Pocket Guide', 'Operating Systems', 25.00, 2018, TRUE, 2),
                                                                                          (52, 'The Linux Command Line', 'Operating Systems', 29.00, 2020, TRUE, 9),
                                                                                          (53, 'Windows Internals', 'Operating Systems', 60.00, 2022, FALSE, 8),
                                                                                          (54, 'Modern Operating Systems', 'Operating Systems', 55.00, 2021, TRUE, 4),
                                                                                          (55, 'Mastering Ubuntu Server', 'Operating Systems', 43.00, 2019, TRUE, 10),

                                                                                          (56, 'Agile Principles', 'Management', 28.00, 2016, TRUE, 3),
                                                                                          (57, 'Scrum Guide', 'Management', 20.00, 2017, TRUE, 3),
                                                                                          (58, 'Project Management Simplified', 'Management', 25.00, 2019, TRUE, 3),
                                                                                          (59, 'Lean Software Development', 'Management', 33.00, 2003, FALSE, 6),
                                                                                          (60, 'Continuous Delivery', 'DevOps', 44.00, 2010, FALSE, 6);

-- Fill up to 100 with duplicates/more variations
-- (Books 61–100: random extra books to enrich test data)
INSERT INTO books (id, title, genre, price, publish_year, availability, publisher_id) VALUES
                                                                                          (61, 'Refactoring to Patterns', 'Programming', 38.00, 2017, TRUE, 6),
                                                                                          (62, 'JUnit in Action', 'Programming', 35.00, 2021, TRUE, 7),
                                                                                          (63, 'Test Driven Development', 'Programming', 42.00, 2010, TRUE, 6),
                                                                                          (64, 'Clean Coder Handbook', 'Programming', 34.00, 2022, TRUE, 6),
                                                                                          (65, 'Pro Git', 'DevOps', 30.00, 2014, TRUE, 10),
                                                                                          (66, 'Git in Practice', 'DevOps', 32.00, 2015, TRUE, 5),
                                                                                          (67, 'Docker Deep Dive', 'DevOps', 39.00, 2018, TRUE, 5),
                                                                                          (68, 'Kubernetes Patterns', 'DevOps', 49.00, 2022, TRUE, 2),
                                                                                          (69, 'Infrastructure as Code', 'DevOps', 48.00, 2021, TRUE, 2),
                                                                                          (70, 'Cloud Native Patterns', 'Architecture', 50.00, 2021, FALSE, 7),

                                                                                          (71, 'Java by Example', 'Programming', 28.00, 2012, TRUE, 6),
                                                                                          (72, 'Effective Kotlin', 'Programming', 44.00, 2021, TRUE, 7),
                                                                                          (73, 'Mastering Spring Boot', 'Programming', 46.00, 2023, FALSE, 7),
                                                                                          (74, 'Designing Data-Intensive Applications', 'Architecture', 59.00, 2017, TRUE, 2),
                                                                                          (75, 'Software Engineering at Google', 'Management', 54.00, 2020, TRUE, 2),
                                                                                          (76, 'The Mythical Man-Month', 'Management', 40.00, 1975, TRUE, 6),
                                                                                          (77, 'Peopleware', 'Management', 35.00, 1987, TRUE, 6),
                                                                                          (78, 'Code Complete', 'Programming', 52.00, 2004, TRUE, 6),
                                                                                          (79, 'The Art of Computer Programming', 'Computer Science', 95.00, 2011, FALSE, 4),
                                                                                          (80, 'Structure and Interpretation of Computer Programs', 'Computer Science', 85.00, 2010, TRUE, 4),

                                                                                          (81, 'Harry Potter and the Sorcerers Stone', 'Fantasy', 15.00, 2001, TRUE, 3),
                                                                                          (82, 'Harry Potter and the Chamber of Secrets', 'Fantasy', 15.50, 2002, TRUE, 3),
                                                                                          (83, 'Harry Potter and the Prisoner of Azkaban', 'Fantasy', 16.00, 2003, TRUE, 3),
                                                                                          (84, 'The Hobbit', 'Fantasy', 14.00, 1937, FALSE, 3),
                                                                                          (85, 'The Lord of the Rings', 'Fantasy', 30.00, 1954, TRUE, 3),

                                                                                          (86, 'Twilight', 'Fiction', 10.00, 2008, TRUE, 3),
                                                                                          (87, 'New Moon', 'Fiction', 11.00, 2009, TRUE, 3),
                                                                                          (88, 'Eclipse', 'Fiction', 12.00, 2010, TRUE, 3),
                                                                                          (89, 'Breaking Dawn', 'Fiction', 13.00, 2011, TRUE, 3),
                                                                                          (90, 'Midnight Sun', 'Fiction', 14.00, 2020, TRUE, 3),

                                                                                          (91, 'Learning Python', 'Programming', 45.00, 2021, TRUE, 2),
                                                                                          (92, 'Fluent Python', 'Programming', 55.00, 2022, TRUE, 2),
                                                                                          (93, 'Effective Python', 'Programming', 47.00, 2019, TRUE, 2),
                                                                                          (94, 'Python Tricks', 'Programming', 35.00, 2018, TRUE, 9),
                                                                                          (95, 'Think Python', 'Programming', 30.00, 2017, FALSE, 9),
                                                                                          (96, 'Python for Data Analysis', 'Programming', 52.00, 2022, TRUE, 2),
                                                                                          (97, 'Python Data Science Handbook', 'Programming', 49.00, 2022, TRUE, 2),
                                                                                          (98, 'Introduction to Machine Learning', 'AI', 53.00, 2020, TRUE, 4),
                                                                                          (99, 'Deep Reinforcement Learning', 'AI', 58.00, 2023, TRUE, 4),
                                                                                          (100, 'AI Ethics', 'AI', 41.00, 2022, TRUE, 3);

-- ==============================
-- AUTHORS
-- ==============================
INSERT INTO book_authors (book_id, author) VALUES
-- Shared authors, multi-author cases, etc.
(1, 'Joshua Bloch'),
(2, 'Robert C. Martin'),
(3, 'Robert C. Martin'),
(4, 'Kathy Sierra'),
(4, 'Bert Bates'),
(5, 'Brian Goetz'),
(6, 'Craig Walls'),
(7, 'Mark Heckler'),
(8, 'Felipe Gutierrez'),
(9, 'K. Siva Prasad Reddy'),
(10, 'Joshua Bloch'),
(11, 'Andrew Hunt'),
(11, 'David Thomas'),
(12, 'Martin Fowler'),
(13, 'Erich Gamma'),
(13, 'Richard Helm'),
(13, 'Ralph Johnson'),
(13, 'John Vlissides'),
(14, 'John Vlissides'),
(14, 'John Douh'),
(15, 'Shirin Douh'),
(16, 'Stuart Russell'),
(16, 'Peter Norvig'),
(17, 'François Chollet'),
(18, 'Aurélien Géron'),
(19, 'Eric Matthes'),
(20, 'Al Sweigart'),
(21, 'Alan Beaulieu'),
(22, 'Anthony Molinaro'),
(23, 'Kristina Chodorow'),
(24, 'Michael Kofler'),
(25, 'Steve Hoberman'),
(26, 'F. Scott Fitzgerald'),
(27, 'George Orwell'),
(28, 'Harper Lee'),
(29, 'J.D. Salinger'),
(30, 'Aldous Huxley'),
(31, 'Aldous Huxley'),
(32, 'Writer No1'),
(33, 'Writer No2'),
(34, 'Writer No3'),
(35, 'Writer No4'),
(36, 'Jon Krohn'),
(37, 'Giancarlo Zaccone'),
(38, 'Joel Grus'),
(39, 'Andrew Ng'),
(40, 'Kai-Fu Lee'),
(41, 'Robert C. Martin'),
(42, 'Eric Evans'),
(43, 'Sam Newman'),
(44, 'Mark Richards'),
(45, 'Gregor Hohpe'),
(45, 'Bobby Woolf'),
(46, 'Dylan Scott'),
(47, 'David Dossot'),
(48, 'Josh Long'),
(49, 'Nigel Poulton'),
(50, 'Brendan Burns'),
(51, 'Daniel Barrett'),
(52, 'William Shotts'),
(53, 'Mark Russinovich'),
(54, 'Andrew S. Tanenbaum'),
(55, 'Jay LaCroix'),
(56, 'Robert C. Martin'),
(57, 'Jeff Sutherland'),
(58, 'John Smith'),
(59, 'Mary Poppendieck'),
(60, 'Jez Humble'),
(61, 'Joshua Kerievsky'),
(62, 'Petar Tahchiev'),
(63, 'Kent Beck'),
(64, 'Robert C. Martin'),
(65, 'Scott Chacon'),
(66, 'Mike McQuaid'),
(67, 'Nigel Poulton'),
(68, 'Bilgin Ibryam'),
(69, 'Kief Morris'),
(70, 'Cornelia Davis'),
(71, 'Joshua Bloch'),
(72, 'Marcin Moskala'),
(73, 'Alex Antonov'),
(74, 'Martin Kleppmann'),
(75, 'Titus Winters'),
(76, 'Frederick P. Brooks'),
(77, 'Tom DeMarco'),
(78, 'Steve McConnell'),
(79, 'Donald Knuth'),
(80, 'Harold Abelson'),
(81, 'J.K. Rowling'),
(82, 'J.K. Rowling'),
(83, 'J.K. Rowling'),
(84, 'J.R.R. Tolkien'),
(85, 'J.R.R. Tolkien'),
(86, 'Stephenie Meyer'),
(87, 'Stephenie Meyer'),
(88, 'Stephenie Meyer'),
(89, 'Stephenie Meyer'),
(90, 'Stephenie Meyer'),
(91, 'Mark Lutz'),
(92, 'Luciano Ramalho'),
(93, 'Brett Slatkin'),
(94, 'Dan Bader'),
(95, 'Allen B. Downey'),
(96, 'Wes McKinney'),
(97, 'Jake VanderPlas'),
(98, 'Ethem Alpaydin'),
(99, 'Richard S. Sutton'),
(100, 'Mark Coeckelbergh');
